env:
  browser: true
  es2021: true
settings:
  react:
    version: detect
extends:
  - 'plugin:react/recommended'
  - 'plugin:react-hooks/recommended'
  - standard
  # - react-app
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
rules: {}
